In [6]:
import pandas as pd
df = pd.read_csv("tmdb_5000_movies.csv")
df1= pd.read_csv("tmdb_5000_credits.csv")
df.columns.values[3] = 'movie_id'
print(df.columns)
print(df1.columns)
movies = df.merge(df1,on = 'movie_id')

Index(['budget', 'genres', 'homepage', 'movie_id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count'],
      dtype='object')
Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [7]:
movies.head()

      budget  ...                                               crew
0  237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1  300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]

In [19]:
def get_genre(row):
  try: 
    return eval(row)[0]['name']
  except IndexError:
    return 'Unknown'
movies['genre_final'] = movies['genres'].apply(get_genre)

In [21]:
def get_region(row):
    try: 
      return eval(row)[0]['name']
    except IndexError:
      return 'Unknown'

movies['region_final'] = movies['production_countries'].apply(get_region)

In [28]:
def get_cast(row):
  lister = []
  try:
    
    for i in eval(row):
      lister.append(i['character'])
    return lister
  except IndexError:
    return lister


movies['cast_final'] = movies['cast'].apply(get_cast)

In [33]:
movies.head()

      budget  ... director
0  237000000  ...
1  300000000  ...
2  245000000  ...
3  250000000  ...
4  260000000  ...

[5 rows x 27 columns]

In [36]:
movies_imp = movies[['original_title', 'overview','region_final', 'release_date', 'genre_final', 'cast_final', 'director']]

In [37]:
movies_imp.head()

                             original_title  ... director
0                                    Avatar  ...
1  Pirates of the Caribbean: At World's End  ...
2                                   Spectre  ...
3                     The Dark Knight Rises  ...
4                               John Carter  ...

[5 rows x 7 columns]

In [39]:
movies_imp.to_csv('movies_final.csv')